---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "kneaddata_readcounts"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::kneaddata=0.12.0"
